---
# Ansible Inventory pÃ«r Staging Environment

all:
  children:
    app_servers:
      hosts:
        smartgrid-staging-01:
          ansible_host: 10.0.2.10
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/smartgrid-staging.pem
      vars:
        environment: staging
        kafka_broker: smartgrid-kafka-staging:9092
        postgres_host: smartgrid-postgres-staging

