services:

  postgres:
    image: postgres:15
    container_name: smartgrid-postgres
    environment:
      POSTGRES_USER: smartgrid
      POSTGRES_PASSWORD: smartgrid123
      POSTGRES_DB: smartgrid_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  postgres-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter:latest
    container_name: smartgrid-postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://smartgrid:smartgrid123@smartgrid-postgres:5432/smartgrid_db?sslmode=disable"
    ports:
      - "9187:9187"
    depends_on:
      - postgres

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: smartgrid-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: smartgrid-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://smartgrid-kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-exporter:
    image: danielqsj/kafka-exporter:latest
    container_name: smartgrid-kafka-exporter
    environment:
      KAFKA_BROKERS: smartgrid-kafka:9092
    ports:
      - "9308:9308"
    depends_on:
      - kafka

  prometheus:
    image: prom/prometheus:latest
    container_name: smartgrid-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ../monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    depends_on:
      - kafka-exporter
      - postgres-exporter

  grafana:
    image: grafana/grafana:latest
    container_name: smartgrid-grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

  api-gateway:
    build: ./api_gateway
    container_name: smartgrid-api-gateway
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - kafka

volumes:
  pgdata:
  grafana_data:
